# Reference
# ICONS: use Font Awesome (fa-code, fa-box) etc
# VARIABLES: (Substituted by the front end)
#   $root - root data path, with https:// prefix
items:
  - name: MissileWarsX
    weight: 9
    tags:
      - java
      - minecraft
      - plugin-development
      - spigot
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/MissileWarsX.git
    image: $root/assets/portfolio/missile-wars.png
    content: |-
      An open source implementation of the legendary MissileWars mini-game originally conceived by SethBling and Cubehamster. MwX is a performant plugin that uses FastAsyncWorldEdit and a plethora of Minecraft internal tricks to run the minigame without lag.
  - name: hosts.net
    weight: 7
    tags:
      - dotnet
      - library
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/hosts.net.git
      - name: Install Package
        icon: fa-box
        link: https://www.nuget.org/packages/hosts.net
    content: |-
      A handy library to edit hosts files in .NET
