# Reference
# ICONS: use Font Awesome (fa-code, fa-box) etc
# VARIABLES & EVALUATION: (Substituted by the front end)
#   $root - root data path prefix, with https:// prefix
#   $blog - blog path prefix
items:
  - name: MissileWarsX
    weight: 8
    tags:
      - java
      - minecraft
      - plugin-development
      - spigot
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/MissileWarsX.git
    image: $root/assets/portfolio/missile-wars.png
    content: |-
      An open source implementation of the legendary MissileWars mini-game originally conceived by SethBling and Cubehamster. MwX is a performant plugin that uses FastAsyncWorldEdit and a plethora of Minecraft internal tricks to run the minigame without lag.
  - name: hosts.net
    weight: 7
    tags:
      - dotnet
      - library
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/hosts.net.git
      - name: Install Package
        icon: fa-box
        link: https://www.nuget.org/packages/hosts.net
    content: |-
      A utility library for managing the hosts file on Windows, Linux and Mac. It currently has the following download count: <img alt="Nuget" src="https://img.shields.io/nuget/dt/hosts.net?style=flat&color=%23ffffff">
  - name: GitRCFS
    weight: 7
    tags:
      - dotnet
      - library
      - git
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/gitrcfs.git
      - name: Install Package
        icon: fa-box
        link: https://www.nuget.org/packages/GitRCFS
    content: |-
      GitRCFS offers a lightweight API to synchronize an application's configuration / data files with a remote git repository. The API is designed in a natural way for rapid prototyping. It currently has the following download count: <img alt="Nuget" src="https://img.shields.io/nuget/dt/GitRCFS?style=flat&color=%23ffffff">
  - name: This Website
    weight: 8
    tags:
      - dotnet
      - javascript
      - svelte
      - kubernetes
    links:
      - name: OpenAPI Spec
        icon: fa-layer-group
        link: https://api.encodeous.ca/swagger/index.html
      - name: Frontend Source
        icon: fa-code
        link: https://github.com/encodeous/spearfish
    content: |-
      This website is the culmination of many technologies, and is a great example of how to use the GitRCFS library. The webpage you are reading right now is generated live from <a class="tangerine" href="https://github.com/encodeous/site-data">this repo</a>. For more info, see <a class="tangerine" href="$blog/spearfish">this blog post</a>.
  - name: WyRIM
    weight: 6
    tags:
      - java
      - minecraft
      - fabric-modding
    image: $root/assets/portfolio/wyrim.png
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/WyRIM.git
      - name: Watch Demo
        icon: fa-video
        link: https://www.youtube.com/watch?v=goahlUHhgWg
    content: |-
      WyRIM is a high-level wrapper UI for the vanilla Wynncraft item bank. It provides a much more user friendly interface by turning the original chest-based UI into a searchable, scrollable and sortable container.
  - name: PaperTime
    weight: 6
    tags:
      - java
      - minecraft
      - server-fork
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/PaperTime.git
    content: |-
      PaperTime is a specialized Paper fork that enables technical players to manipulate the game speed (TPS) using an in-game command. This was made long before Mojang added this feature to the native game.
  - name: 4Plumbers
    weight: 8
    tags:
      - javascript
      - web-design
      - client
      - astrojs
    links:
      - name: View Site
        icon: fa-link
        link: https://4plumbers.ca/
    content: |-
      Developed a client website for a plumbing company in the local area. The site was built in Astro, and hosted on Cloudflare.
  - name: Goldfish
    weight: 9
    tags:
      - dotnet
      - algorithms
      - library
      - cli
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/goldfish.git
      - name: API Docs
        icon: fa-file
        link: https://encodeous.github.io/goldfish/
    content: |-
      Goldfish is a complete Chess Engine and framework for chess written entirely in .NET. The engine uses techniques such as Alpha-Beta pruning, Transposition Tables, Iterative Deepening, and concurrent/parallel search to achieve a high level of performance. The engine is relatively strong, and can beat most casual players at an Elo of around 1600.
  - name: A Very Simple Pong Game
    weight: 2
    tags:
      - java
      - swing
      - networking
      - game
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/a-very-simple-pong-game.git
    content: |-
      A simple pong game written in Java using Swing. The game supports multiplayer over a local network, and has a simple AI for single player mode.
  - name: EmojiPad
    weight: 7
    tags:
      - dotnet
      - wpf
      - windows
    image: $root/assets/portfolio/emojipad.png
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/emojipad.git
    content: |-
      EmojiPad is a highly configurable emoji sticker pad. Its sleek UI is simple to use, and handles thousands of emojis with ease.
  - name: VirtualEdit
    weight: 8
    tags:
      - java
      - minecraft
      - library
      - algorithms
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/VirtualEdit.git
    content: |-
      VirtualEdit is an experimental library for Paper that allows developers to modify vast regions of the world (seen by the client) without causing lag. This is accomplished by using an internal 3d implicit segment tree and real-time packet manipulation. This library is used in MissileWarsX to hide entire regions of the world from the client.
  - name: Neutrino
    weight: 8
    tags:
      - dotnet
      - cli
      - algorithms
      - library
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/Neutrino.git
      - name: Install Package
        icon: fa-box
        link: https://www.nuget.org/packages/Neutrino.Cli
    content: |-
      Neutrino is a command line tool and library for performing fast full-text search. It uses an extended rolling hash algorithm to achieve O(n) time complexity while allowing advanced search features such as wildcards and file globbing. This is still a WIP project.
  - name: JourneyRoute
    weight: 9
    tags:
      - java
      - minecraft
      - algorithms
    image: $root/assets/portfolio/journeyroute.png
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/journeyroute.git
      - name: Watch Demo
        icon: fa-video
        link: https://www.youtube.com/watch?v=d2jtADDBxpM
    content: |-
      JourneyRoute is a path-finding mod for Minecraft. With JourneyRoute, you will never get lost down a mineshaft! As you travel in a world, it will build a network of all the places you have been, and is able to find routes between locations. It uses the A* algorithm to efficiently search through its internal 3d graph of the world.
  - name: EtfDotNet
    weight: 9
    tags:
      - dotnet
      - erlang-term-format
      - library
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/EpicPix/EtfDotNet.git
    content: |-
      EtfDotNet is a high performance library for serializing and deserializing Erlang Term Format (ETF). It is able to deserialize most data in-place without having to copy it into new buffers.
  - name: Offline Judge
    weight: 9
    image: $root/assets/portfolio/offlinejudge.png
    tags:
      - dotnet
      - cli
      - competitive-programming
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/offlinejudge.git
    content: |-
      Offline Judge is a command line tool for testing competitive programming solutions. It is able to run solutions against a reference solution, and compare the output. It runs solutions in parallel, and is able to terminate solutions that exceed the time or memory limit.
  - name: Musii
    weight: 7
    tags:
      - dotnet
      - discord-bot
      - self-hosted
    links:
      - name: Learn More
        icon: fa-plus
        link: https://github.com/encodeous/musii.git
    content: |-
      Musii is a self-hosted Discord bot that allows users to play music in Discord voice channels. It is able to play music from YouTube, SoundCloud, and Spotify (by searching for the song on YouTube). It also has a built-in queue system, and supports playlists, bass boost, sharing playlists, and more.
  - name: Clockwork
    weight: 8
    tags:
      - dotnet
      - task-scheduling
      - library
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/clockwork.git
      - name: Install Package
        icon: fa-box
        link: https://www.nuget.org/packages/Encodeous.clockwork/
    content: |-
      Clockwork is a declarative & fluent task scheduling library for .NET. It allows you to schedule tasks to run at specific times, or at regular intervals. It also supports running tasks in parallel, and is built on top of the Task Parallel Library.