# Reference
# ICONS: use Font Awesome (fa-code, fa-box) etc
# VARIABLES & EVALUATION: (Substituted by the front end)
#   $root - root data path prefix, with https:// prefix
#   $blog - blog path prefix
items:
  - name: MissileWarsX
    weight: 9
    tags:
      - java
      - minecraft
      - plugin-development
      - spigot
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/MissileWarsX.git
    image: $root/assets/portfolio/missile-wars.png
    content: |-
      An open source implementation of the legendary MissileWars mini-game originally conceived by SethBling and Cubehamster. MwX is a performant plugin that uses FastAsyncWorldEdit and a plethora of Minecraft internal tricks to run the minigame without lag.
  - name: hosts.net
    weight: 7
    tags:
      - dotnet
      - library
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/hosts.net.git
      - name: Install Package
        icon: fa-box
        link: https://www.nuget.org/packages/hosts.net
    content: |-
      A utility library for managing the hosts file on Windows, Linux and Mac. As of writing, it has been installed <img alt="Nuget" src="https://img.shields.io/nuget/dt/hosts.net?style=flat&color=%23ffffff"> times.
 downloads on NuGet.
  - name: GitRCFS
    weight: 7
    tags:
      - dotnet
      - library
      - git
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/gitrcfs.git
      - name: Install Package
        icon: fa-box
        link: https://www.nuget.org/packages/GitRCFS
    content: |-
      GitRCFS offers a lightweight API to synchronize an application's configuration / data files with a remote git repository. The API is designed in a natural way for rapid prototyping.
  - name: This Website
    weight: 8
    tags:
      - dotnet
      - svelte
      - kubernetes
    links:
      - name: OpenAPI Spec
        icon: fa-layer-group
        link: https://api.encodeous.ca/swagger/index.html
      - name: Frontend Source
        icon: fa-code
        link: https://github.com/encodeous/spearfish
    content: |-
      This website is the culmination of many technologies, and is a great example of how to use the GitRCFS library. The webpage you are reading right now is generated live from <a class="tangerine" href="https://github.com/encodeous/site-data">this repo</a>. For more info, see <a class="tangerine" href="$blog/spearfish">this blog post</a>.
  - name: WyRIM
    weight: 6
    tags:
      - java
      - minecraft
      - fabric-modding
    image: $root/assets/portfolio/wyrim.png
    links:
      - name: Source Code
        icon: fa-code
        link: https://github.com/encodeous/WyRIM.git
      - name: Watch Demo
        icon: fa-video
        link: https://www.youtube.com/watch?v=goahlUHhgWg
    content: |-
      WyRIM is a high-level wrapper UI for the vanilla Wynncraft item bank. It provides a much more user friendly interface by the original chest-based UI into a searchable, scrollable and sortable container.
